### ISSUE TITLE
Release 0.2.1 registers with Windows Defender as Trojan:Win32/Fuery.B!cl

### ISSUE THREAD

**Issue by mmyang** [Mpstark/BattleTechModLoader#17]
![trojan_win32_fuery](https://user-images.githubusercontent.com/1436002/40575205-7627c3e6-6095-11e8-9c30-9ddc9a3c53b2.JPG)

**Comment by Mpstark** [comment]
This is unfortunately something that we have to live with. I can look into getting BTML signed, but ultimately we are injecting code into another program.

**Comment by Mpstark** [comment]
We're working on trying to convince HBS to add BTML to the base game. Obviously this will be a process and they're likely to say "no", but we can hope. It's honestly a fairly simple process with not much code involved.

Distributing a pre-patched assembly might be an alright solution for users that feel uncomfortable using the injector. I'll ask around and see what others think of it.

I don't know about the installer/manager thing. @Cptmoore has his own installer/launcher project, but I don't know much about it. It's here: https://github.com/CptMoore/BattleTechModTools

Personally, I think something like [CKAN](https://github.com/KSP-CKAN/CKAN) is the right way to go, if someone wanted to tackle that.

**Comment by CptMoore** [comment]
> I'm just starting the process of designing a ModTek Installer/Manager. In addition to handling the execution of the BTML injector

good idea, if you need an installer for your manager, you can use my installer as a base. see https://github.com/CptMoore/BattleTechModTools/blob/tools/BattleTechModInstaller/InstallerScript.iss

I'm waiting for Mpstark to give me his ok to release that installer to Nexus. He stated he wants to wait until ModTek is mature enough to even consider an installer. If you of course have a nice manager by then, that would allow me to retire the installer.

**Comment by jelster** [comment]
KSP/CKAN is precisely the model I’ve been using for inspiration, @michaelstarkweather!

There’s a long way to go until we get to the maturity of the KSP modding ecosystem but it’s looking promising so far.

I’ll take a look at your installer, @cptmoore - I certainly like the idea of us all coordinating our efforts instead of duplicating each other’s mistakes!

To that end, maybe it’s too early to discuss but at what point does it make sense to create a GH Org or something to contain all these related pieces of work that interdepend on each other in some way?

________________________________

**Comment by YoungCP** [comment]
Might be as simple as renaming the executable, maybe signing built releases, ...

Have you tried to see if renaming the executable got around the error?
